@startuml
title v1.0-验收流程

|总控平台|
start
partition 基础流程 {
:创建合伙人;
:实名合伙人;
:初始化账号;
|#AntiqueWhite|合伙人APP|
:登录APP;
:重置APP密码;
:添加客户;
:添加订单;
:订单支付;
:出账生成;
:检查出账;
|总控平台|
:订单发货;
}

partition 入账验收 {
|合伙人APP|
:账务充值;
|总控平台|
:入账审核;
|合伙人APP|
:入账检查;
}

partition 出账验收 {
:账务提现;
|总控平台|
:出账审核;
|合伙人APP|
:出账检查;
}
stop
@enduml
