@startuml

package 合伙人app <<Frame>> {
    class 客户余额 {
        Integer 余额ID
        Integer 金额（入账、出账金额，有正有负）
        String 类型（充值、退款、分润等）
        String 备注
        Integer 账务ID
    }
    
    class 客户账务 {
        Integer 账务ID
        Integer 合伙人ID
        Integer 金额（入账、出账金额，有正有负）
        String 类型（充值、退款、分润等）
        Integer 来源ID
        String 备注
        Datetime 创建时间
    }


    客户账务 <.. 客户余额: 关联
}


package 平台 <<Frame>> {

    package 客户账务管理 <<Rectangle>> {
    
        class 入账单 {
            Integer 入账ID
            Integer 合伙人ID
            Integer 应入账金额
            Integer 实入账金额
            Datetime 应入账时间
            Datetime 实际账时间
            String 入账状态（入账中，已入账，入账失败）
            String 来源（结算、订单、奖励、其他）
            Integer 来源ID
            Integer 账务ID
            String 备注
            Datetime 更新时间
            Datetime 创建时间
        }
        
        class 出账单 {
            Integer 出账ID
            Integer 合伙人ID
            Integer 应出账金额
            Integer 实出账金额
            Datetime 应出账时间
            Datetime 实出账时间
            String 出账状态（出账中，已出账，出账失败）
            String 来源（提现、站内支付、其他）
            Integer 来源ID
            Integer 账务ID
            String 备注
            Datetime 更新时间
            Datetime 创建时间
        }
        
        
        class 审核事件 {
            Integer 审核ID
            Integer 合伙人ID
            Integer 审核人ID
            String 快照内容
            String 审核类型（入账单、出账单、其他）
            Integer 审核对象ID
            String 审核状态（通过、失败）
            Datetime 创建时间
        }


       	审核事件 ..> 入账单 : 绑定
        审核事件 ..> 出账单 : 绑定
    }


    package 平台账务管理 <<Rectangle>> {
        class 平台账务 {
            Integer 账务ID
            Integer 合伙人ID
            Integer 金额（入账、出账金额，有正有负）
            Integer 类型（订单、结算、充值、扣除等）
            Datetime 创建时间
        }
    }
}

客户余额 <-[#blue]-> 入账单 : 双重绑定
客户余额 <-[#blue]-> 出账单 : 双重绑定
客户账务 -[#blue]-> 平台账务: 生成

@enduml
