@startuml
frame 账号管理 {
storage 账号
storage 授权
}



frame 合伙人 {
storage 实名认证
storage 个人信息

实名认证 ..> 个人信息
}


frame 客户管理 {
storage 客户
storage 地址
storage 动态

客户 <.. 地址
客户 <.. 动态
}



frame 设备管理 {
storage 设备
storage 商户
storage 流水

设备 ..> 商户
商户 ..> 流水
}



frame 订单管理 {
storage 订单
storage 需求快照
storage 支付凭证
storage 物流信息
storage 退款补货

订单 ..> 需求快照
订单 ..> 支付凭证
订单 ..> 物流信息
订单 ..> 退款补货
}


frame 库存管理 {
storage 产品
storage 商品

产品 ..> 商品
}


frame 结算管理 {
storage 政策
storage 结算凭证

政策 ..> 结算凭证
}



frame 余额管理 {
storage 余额
storage 提现记录
storage 充值记录

余额 ..> 提现记录
余额 <.. 充值记录
}

frame 账务管理 {
storage 交易记录
}


frame 工作流 #red {
storage 入账单
storage 出账单
}


frame 事件管理 #red {
storage 实名事件
storage 发货事件
storage 补货事件
storage 退款事件
storage 入账审核事件
storage 出账审核事件
}


个人信息 -[#blue]-> 账号: 生成
个人信息 -[#blue]-> 授权: 授权
个人信息 -[#blue]-> 客户: 添加
客户 -[#blue]-> 订单: 生成
商品 -[#blue]-> 订单: 依赖
物流信息 -[#blue]-> 设备: 发货
政策 -[#blue]-> 设备: 绑定
设备 -[#blue]-> 结算凭证: 计算
流水 -[#blue]-> 结算凭证: 计算
商户 -[#blue]-> 结算凭证: 计算
结算凭证 -[#blue]-> 余额: 对账
客户 <-[#blue]- 设备: 归属
政策 -[#blue]-> 产品: 绑定
支付凭证 -[#blue]-> 交易记录: 生成
交易记录 -[#blue]-> 个人信息: 归属
提现记录 -[#blue]-> 交易记录: 同步
充值记录 -[#blue]-> 交易记录: 同步
入账单 --> 充值记录
提现记录 --> 出账单

实名认证 <.[#green]. 实名事件: 生成
发货事件 <.[#green]. 物流信息: 生成
退款事件 <.[#green]. 退款补货: 生成
补货事件 <.[#green]. 退款补货: 生成
入账审核事件 <.[#green]. 入账单: 审核
出账审核事件 <.[#green]. 出账单: 审核

@enduml
